# .platform.app.yaml

name: html-app
type: "php:8.0"

build:
    flavor: none

mounts:
    "/web": "shared:files"

web:
    locations:
        "/":
            root: "/web"
            passthru: "/index.html"

