{
    "https://main-bvxea6i-iogixy7752ace.us.platformsh.site/": {
        "primary": true,
        "id": null,
        "attributes": {},
        "type": "upstream",
        "upstream": "app",
        "original_url": "http://www.careers.unity.com/"
    }
}    