# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://main-bvxea6i-iogixy7752ace.us.platformsh.site/":
    type: upstream
    upstream: "app:http"

"https://main-bvxea6i-iogixy7752ace.us.platformsh.site/":
    type: redirect
    to: "https://main-bvxea6i-iogixy7752ace.us.platformsh.site/"
